
on:
  pull_request:
jobs:
  gate:
    needs: a
    runs-on: ubuntu-latest
    steps:
      - name: Run it
        run: run-the-gate
  a:
    needs: b
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
  b:
    needs: a
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
