import path from 'node:path';

/**
 * Fixture app for the dev-phase half of the guarded-instrumentation fence
 * (#408, follow-up to #356/ADR-0031).
 *
 * Deliberately minimal and dependency-free: `middleware.ts` forces an EDGE
 * compile, `instrumentation.ts` is edge-clean and dynamic-imports
 * `instrumentation-node.ts`, which statically imports Node core modules that do
 * NOT exist on the edge runtime. That is the exact shape #342/#356 fenced for
 * `phase-production-build`; this fixture is what `next dev` is measured against
 * by `../../adapter-dev-edge-fence.test.ts`.
 */
export default {
  // The fixture lives inside the monorepo; pin the bundler root at the repo root
  // so Turbopack does not refuse to compile files "outside the project".
  turbopack: { root: path.resolve(import.meta.dirname, '../../../../../..') },
  // `.knext/adapter.mjs` is GENERATED by adapter-dev-edge-fence.test.ts, which
  // esbuild-bundles the adapter SOURCE into it. That keeps the fixture pinned to
  // the code under test with no dependency on a prior package build — and if the
  // bundle is absent, `next dev` fails loudly rather than silently skipping.
  adapterPath: path.resolve(import.meta.dirname, '.knext/adapter.mjs'),
};
