
on:
  pull_request:
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - name: Optional setup
        if: ${{ runner.os == 'Linux' }}
        run: echo hi
      - name: Run it
        run: run-the-gate
