
on:
  pull_request:
jobs:
  gate:
    timeout-minutes: 30
    name: Gate
    runs-on: ubuntu-latest
    steps:
      - name: Run it
        run: run-the-gate
  other:
    name: Other
    runs-on: ubuntu-latest
    steps:
      - name: Something
        run: echo hi
