
on:
  pull_request:
jobs:
  gate:
    name: Gate
    runs-on: ubuntu-latest
    steps:
      - name: Run it
        run: something-else
  other:
    name: Other
    runs-on: ubuntu-latest
    steps:
      - name: Something
        run: echo hi
