/**
 * The committed `bun.lock` must not be silently downgraded (#879).
 *
 * ## The trap, measured
 *
 * `bun install --frozen-lockfile` fails for anyone whose local bun is older than
 * the one that wrote the lockfile:
 *
 *   warn: Ignoring lockfile
 *   error: lockfile had changes, but lockfile is frozen
 *   note: try re-running without --frozen-lockfile and commit the updated lockfile
 *
 * Following that note on bun 1.3.5, against a v3 lockfile written by 1.4.0:
 *
 *   lockfileVersion   3  ->  1
 *   packages          1049 installs / 1288 packages  ->  557
 *   `fast-xml-parser` override                        ->  DROPPED
 *
 * The same command on 1.4.0 produces a six-line diff. So the failure mode is not
 * "install refuses" — it is "install refuses, tells you to regenerate, and
 * regenerating halves your dependency tree and removes a security override", in
 * a 1988-line diff. That is exactly the size at which a reviewer stops reading a
 * lockfile diff.
 *
 * ## Why this is a guard and not a version pin
 *
 * Declaring the version does not work, and that was measured rather than
 * assumed: bun 1.3.5 runs `bun install` happily against BOTH
 * `packageManager: "bun@1.4.0"` and a `.bun-version` file. Neither makes bun
 * refuse or switch — they are read by version MANAGERS (mise, proto, asdf), not
 * by bun itself. A pin nobody enforces is documentation, and documentation does
 * not survive a contributor following an error message's own advice.
 *
 * So the check lives where the damage becomes permanent: the commit.
 */

import { describe, expect, it } from 'bun:test';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const lockText = () => readFileSync(resolve(repoRoot, 'bun.lock'), 'utf8');
const manifest = () =>
  JSON.parse(readFileSync(resolve(repoRoot, 'package.json'), 'utf8')) as {
    overrides?: Record<string, unknown>;
    packageManager?: string;
  };

describe('bun.lock integrity (#879)', () => {
  it('is lockfileVersion 3 — the version an older bun silently downgrades', () => {
    // The single clearest signal that a wrong bun rewrote it. A downgrade to 1
    // is what carried the dropped override and the halved tree.
    const version = lockText().match(/"lockfileVersion":\s*(\d+)/)?.[1];
    expect(
      version,
      'bun.lock has no lockfileVersion — the format changed or the file is truncated',
    ).toBeDefined();
    expect(
      Number(version),
      'bun.lock was written by an older bun (lockfileVersion < 3). Regenerating on ' +
        'the wrong version halves the dependency tree and drops security overrides; ' +
        'install with the bun in `packageManager` and commit that lockfile instead.',
    ).toBe(3);
  });

  it('carries every override package.json declares', () => {
    // The overrides are SECURITY controls — pinned floors for advisories. A
    // downgrade drops them from the lockfile while leaving them in
    // `package.json`, so the declaration still reads correct and the installed
    // tree no longer honours it. Nothing else in the suite would notice.
    //
    // Scanned from the declaration, not enumerated here: adding a 13th override
    // is covered the moment it is declared.
    const declared = Object.keys(manifest().overrides ?? {});
    expect(
      declared.length,
      'package.json declares no overrides — this guard has no subject',
    ).toBeGreaterThan(0);

    const lock = lockText();
    const missing = declared.filter((name) => !lock.includes(`"${name}"`));
    expect(
      missing,
      'these overrides are declared in package.json but absent from bun.lock — the ' +
        'lockfile was regenerated by a bun that does not understand them, so the ' +
        'installed tree does not honour the pinned floors',
    ).toEqual([]);
  });

  it('the lockfile is a plausible size for this workspace', () => {
    // The downgrade produced 557 packages where 1288 were expected. An exact
    // count would red on every ordinary dependency change, so this is a floor
    // set far below the real figure — it catches a halving, not a bump.
    const entries = (lockText().match(/^\s{4}"[^"]+": \[/gm) ?? []).length;
    expect(
      entries,
      `bun.lock lists ${entries} packages, far fewer than this workspace resolves. ` +
        'That is the signature of a lockfile regenerated by the wrong bun.',
    ).toBeGreaterThan(800);
  });

  it('packageManager names the bun the lockfile was written by', () => {
    // Not enforcement — measured: bun ignores this field. It is the only place
    // recording WHICH version to install with, so the error messages above can
    // point at it. If it stops naming bun, they point at nothing.
    expect(manifest().packageManager).toMatch(/^bun@\d+\.\d+\.\d+$/);
  });
});
