/**
 * The committed `bun.lock` must not be silently downgraded (#879).
 *
 * ## The trap, measured
 *
 * `bun install --frozen-lockfile` fails for anyone whose local bun is older than
 * the one that wrote the lockfile:
 *
 *   warn: Ignoring lockfile
 *   error: lockfile had changes, but lockfile is frozen
 *   note: try re-running without --frozen-lockfile and commit the updated lockfile
 *
 * Following that note on bun 1.3.5, against a v3 lockfile written by 1.4.0:
 *
 *   lockfileVersion   3  ->  1
 *   packages          1049 installs / 1288 packages  ->  557
 *   `fast-xml-parser` override                        ->  DROPPED
 *
 * The same command on 1.4.0 produces a six-line diff. So the failure mode is not
 * "install refuses" — it is "install refuses, tells you to regenerate, and
 * regenerating halves your dependency tree and removes a security override", in
 * a 1988-line diff. That is exactly the size at which a reviewer stops reading a
 * lockfile diff.
 *
 * ## Why this is a guard and not a version pin
 *
 * Declaring the version does not work, and that was measured rather than
 * assumed: bun 1.3.5 runs `bun install` happily against BOTH
 * `packageManager: "bun@1.4.0"` and a `.bun-version` file. Neither makes bun
 * refuse or switch — they are read by version MANAGERS (mise, proto, asdf), not
 * by bun itself. A pin nobody enforces is documentation, and documentation does
 * not survive a contributor following an error message's own advice.
 *
 * So the check lives where the damage becomes permanent: the commit.
 */

import { describe, expect, it } from 'bun:test';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const lockText = () => readFileSync(resolve(repoRoot, 'bun.lock'), 'utf8');
const manifest = () =>
  JSON.parse(readFileSync(resolve(repoRoot, 'package.json'), 'utf8')) as {
    overrides?: Record<string, unknown>;
    packageManager?: string;
  };

describe('bun.lock integrity (#879)', () => {
  it('is lockfileVersion 3 — the version an older bun silently downgrades', () => {
    // The single clearest signal that a wrong bun rewrote it. A downgrade to 1
    // is what carried the dropped override and the halved tree.
    const version = lockText().match(/"lockfileVersion":\s*(\d+)/)?.[1];
    expect(
      version,
      'bun.lock has no lockfileVersion — the format changed or the file is truncated',
    ).toBeDefined();
    expect(
      Number(version),
      'bun.lock was written by an older bun (lockfileVersion < 3). Regenerating on ' +
        'the wrong version halves the dependency tree and drops security overrides; ' +
        'install with the bun in `packageManager` and commit that lockfile instead.',
    ).toBe(3);
  });

  it('carries every override package.json declares', () => {
    // The overrides are SECURITY controls — pinned floors for advisories. A
    // downgrade drops them from the lockfile while leaving them in
    // `package.json`, so the declaration still reads correct and the installed
    // tree no longer honours it. Nothing else in the suite would notice.
    //
    // Scanned from the declaration, not enumerated here: adding a 13th override
    // is covered the moment it is declared.
    const declared = Object.keys(manifest().overrides ?? {});
    expect(
      declared.length,
      'package.json declares no overrides — this guard has no subject',
    ).toBeGreaterThan(0);

    const lock = lockText();
    const missing = declared.filter((name) => !lock.includes(`"${name}"`));
    expect(
      missing,
      'these overrides are declared in package.json but absent from bun.lock — the ' +
        'lockfile was regenerated by a bun that does not understand them, so the ' +
        'installed tree does not honour the pinned floors',
    ).toEqual([]);
  });

  it('the lockfile is a plausible size for this workspace', () => {
    // The downgrade produced 557 packages where 1288 were expected. An exact
    // count would red on every ordinary dependency change, so this is a floor
    // set far below the real figure — it catches a halving, not a bump.
    const entries = (lockText().match(/^\s{4}"[^"]+": \[/gm) ?? []).length;
    expect(
      entries,
      `bun.lock lists ${entries} packages, far fewer than this workspace resolves. ` +
        'That is the signature of a lockfile regenerated by the wrong bun.',
    ).toBeGreaterThan(800);
  });

  it('resolves no browserslist below the CVE-2026-73088/73089 fix line (#888)', () => {
    // The docs-closure nightly went green only because its scan was re-scoped to
    // a prod-only SBOM (73e265aa), which excludes the dev/build toolchain that
    // pulls the vulnerable line. The lockfile itself still resolved
    // browserslist@4.28.1 (via @babel/helper-compilation-targets), which carries
    // the two HIGH CVEs. Per the bump-don't-suppress discipline, the floor is
    // enforced by a top-level override and proved here against the lockfile.
    const versions = [...lockText().matchAll(/browserslist@(\d+)\.(\d+)\.(\d+)/g)];
    expect(
      versions.length,
      'no browserslist resolution found in bun.lock — the guard has no subject',
    ).toBeGreaterThan(0);
    const below = versions
      .map((m) => ({ raw: m[0], t: [Number(m[1]), Number(m[2]), Number(m[3])] as const }))
      .filter(({ t }) => t[0] < 4 || (t[0] === 4 && (t[1] < 28 || (t[1] === 28 && t[2] < 7))));
    expect(
      below.map((b) => b.raw),
      'bun.lock still resolves a browserslist below 4.28.7, which carries ' +
        'CVE-2026-73088/73089 (HIGH). Raise the top-level `browserslist` override ' +
        'floor and relock; do not suppress the finding.',
    ).toEqual([]);
  });

  it('declares the browserslist override floor at or above the fix line (#888)', () => {
    const floor = manifest().overrides?.browserslist;
    expect(
      floor,
      'package.json declares no `browserslist` override — the CVE-2026-73088/73089 ' +
        'floor is what keeps the babel-pulled 4.28.1 from resolving',
    ).toBeDefined();
    // Must pin a floor of at least 4.28.7 (the fixed line).
    const min = String(floor).match(/>=\s*(\d+)\.(\d+)\.(\d+)/);
    expect(min, 'the browserslist override does not express a `>=x.y.z` floor').not.toBeNull();
    const [maj, minr, pat] = [Number(min?.[1]), Number(min?.[2]), Number(min?.[3])];
    expect(
      maj > 4 || (maj === 4 && (minr > 28 || (minr === 28 && pat >= 7))),
      'the browserslist override floor is below 4.28.7, the CVE fix line',
    ).toBe(true);
  });

  // The three OpenTelemetry HIGH advisories that surfaced during the #888
  // lockfile scan but were out of that task's scope (dev-toolchain browserslist).
  // All three arrive transitively through `@opentelemetry/sdk-node` — a direct
  // dep of apps/file-manager pulled in by @vercel/otel — which pins both leaves
  // exactly, so a coherent sdk-node bump is what moves the set. The advisory DB
  // also names sdk-node itself as affected/fixed, so bumping only the leaves
  // would leave the sdk-node row red — sdk-node carries its own floor here.
  //
  //   @opentelemetry/exporter-prometheus < 0.217.0  CVE-2026-44902 (HIGH)
  //   @opentelemetry/sdk-node            < 0.217.0  CVE-2026-44902 (HIGH)
  //   @opentelemetry/propagator-jaeger   < 2.9.0    CVE-2026-59892 (HIGH)
  //
  // Fixed at source (top-level overrides + relock), not suppressed — the same
  // bump-don't-suppress discipline as the browserslist guards above.
  const otelFloors: ReadonlyArray<{ pkg: string; floor: readonly [number, number, number] }> = [
    { pkg: '@opentelemetry/exporter-prometheus', floor: [0, 217, 0] },
    { pkg: '@opentelemetry/sdk-node', floor: [0, 217, 0] },
    { pkg: '@opentelemetry/propagator-jaeger', floor: [2, 9, 0] },
  ];

  const below = (t: readonly [number, number, number], floor: readonly [number, number, number]) =>
    t[0] < floor[0] ||
    (t[0] === floor[0] && (t[1] < floor[1] || (t[1] === floor[1] && t[2] < floor[2])));

  for (const { pkg, floor } of otelFloors) {
    it(`resolves no ${pkg} below ${floor.join('.')} — the CVE-2026-44902/59892 fix line (#s7-a2)`, () => {
      const escaped = pkg.replace(/[/\\^$*+?.()|[\]{}]/g, '\\$&');
      const versions = [
        ...lockText().matchAll(new RegExp(`${escaped}@(\\d+)\\.(\\d+)\\.(\\d+)`, 'g')),
      ];
      expect(
        versions.length,
        `no ${pkg} resolution found in bun.lock — the guard has no subject`,
      ).toBeGreaterThan(0);
      const bad = versions
        .map((m) => ({ raw: m[0], t: [Number(m[1]), Number(m[2]), Number(m[3])] as const }))
        .filter(({ t }) => below(t, floor));
      expect(
        bad.map((b) => b.raw),
        `bun.lock still resolves ${pkg} below ${floor.join('.')}, which carries a HIGH ` +
          '(CVE-2026-44902 / CVE-2026-59892). Raise the top-level override floor and relock; ' +
          'do not suppress the finding.',
      ).toEqual([]);
    });

    it(`declares the ${pkg} override floor at or above ${floor.join('.')} (#s7-a2)`, () => {
      const declared = manifest().overrides?.[pkg];
      expect(
        declared,
        `package.json declares no \`${pkg}\` override — the floor is what keeps the ` +
          'vulnerable sdk-node-pulled line from resolving',
      ).toBeDefined();
      const min = String(declared).match(/>=\s*(\d+)\.(\d+)\.(\d+)/);
      expect(min, `the ${pkg} override does not express a \`>=x.y.z\` floor`).not.toBeNull();
      const t = [Number(min?.[1]), Number(min?.[2]), Number(min?.[3])] as const;
      expect(
        below(t, floor),
        `the ${pkg} override floor is below ${floor.join('.')}, the CVE fix line`,
      ).toBe(false);
    });
  }

  // GHSA-58mr-gqgx-xq4g / GHSA-qw65-cvwx-89v3 (fast-uri < 3.1.7). Arrives
  // transitively via `ajv@8.20.0` (a dep of `schema-utils`, part of the
  // webpack/build toolchain), which pins `fast-uri` at exactly `3.1.6` in its
  // own package.json — a caret range elsewhere in the tree does not subsume
  // an exact-pinned transitive leaf. Fixed at source (top-level override +
  // relock), same bump-don't-suppress discipline as the rest of this block.
  it('resolves no fast-uri below 3.1.7 — the GHSA-58mr-gqgx-xq4g/GHSA-qw65-cvwx-89v3 fix line', () => {
    const floor = [3, 1, 7] as const;
    const versions = [...lockText().matchAll(/fast-uri@(\d+)\.(\d+)\.(\d+)/g)];
    expect(
      versions.length,
      'no fast-uri resolution found in bun.lock — the guard has no subject',
    ).toBeGreaterThan(0);
    const bad = versions
      .map((m) => ({ raw: m[0], t: [Number(m[1]), Number(m[2]), Number(m[3])] as const }))
      .filter(({ t }) => below(t, floor));
    expect(
      bad.map((b) => b.raw),
      'bun.lock still resolves fast-uri below 3.1.7, which carries two HIGHs ' +
        '(GHSA-58mr-gqgx-xq4g, GHSA-qw65-cvwx-89v3). Raise the top-level `fast-uri` ' +
        'override floor and relock; do not suppress the finding.',
    ).toEqual([]);
  });

  it('declares the fast-uri override floor at or above 3.1.7', () => {
    const declared = manifest().overrides?.['fast-uri'];
    expect(
      declared,
      'package.json declares no `fast-uri` override — the floor is what keeps the ' +
        'ajv-pulled 3.1.6 line from resolving',
    ).toBeDefined();
    const min = String(declared).match(/>=\s*(\d+)\.(\d+)\.(\d+)/);
    expect(min, 'the fast-uri override does not express a `>=x.y.z` floor').not.toBeNull();
    const t = [Number(min?.[1]), Number(min?.[2]), Number(min?.[3])] as const;
    expect(
      below(t, [3, 1, 7]),
      'the fast-uri override floor is below 3.1.7, the GHSA-58mr-gqgx-xq4g/GHSA-qw65-cvwx-89v3 fix line',
    ).toBe(false);
  });

  it('packageManager names the bun the lockfile was written by', () => {
    // Not enforcement — measured: bun ignores this field. It is the only place
    // recording WHICH version to install with, so the error messages above can
    // point at it. If it stops naming bun, they point at nothing.
    expect(manifest().packageManager).toMatch(/^bun@\d+\.\d+\.\d+$/);
  });
});
