// Renders unpinned-fetches.json into the README's "Still not pinned" block, so the list the guard
// enforces and the list a reader sees are one artifact. `node infra/bun-base/unpinned.mjs --write`
// regenerates the README block; tests/bun-base-supply-chain.test.ts fails if it has drifted.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = dirname(fileURLToPath(import.meta.url));
export const BEGIN = '<!-- unpinned-fetches:begin (generated by unpinned.mjs — do not edit) -->';
export const END = '<!-- unpinned-fetches:end -->';

export function entries() {
  return JSON.parse(readFileSync(resolve(dir, 'unpinned-fetches.json'), 'utf8'));
}

export function render() {
  // `match` and `calls` are rendered too: a widened regex (or a changed call count) is then a
  // visible README drift, not a silent edit to a JSON field nobody reads.
  const lines = entries().map((e) => {
    const m = e.match
      ? ` Matches \`${e.match}\` (${e.calls} call${e.calls === 1 ? '' : 's'}).`
      : '';
    return `- **${e.what}** (\`${e.scope}\`) — ${e.why}${m}`;
  });
  return `${BEGIN}\n${lines.join('\n')}\n${END}`;
}

if (process.argv[2] === '--write') {
  const readme = resolve(dir, 'README.md');
  const text = readFileSync(readme, 'utf8');
  const a = text.indexOf(BEGIN);
  const b = text.indexOf(END);
  if (a < 0 || b < a) throw new Error('README.md has no unpinned-fetches markers');
  writeFileSync(readme, text.slice(0, a) + render() + text.slice(b + END.length));
}
