FROM alpine:3.22@sha256:14358309a308569c32bdc37e2e0e9694be33a9d99e68afb0f5ff33cc1f695dce
RUN apk add --no-cache libstdc++ libgcc
WORKDIR /app
COPY fm-knext-x64 /app/server
COPY .output/public /app/.output/public
USER 65532:65532
ENV PORT=3000 METRICS_PORT=9091
EXPOSE 3000 9091
CMD ["/app/server"]
