FROM alpine:3.22@sha256:14358309a308569c32bdc37e2e0e9694be33a9d99e68afb0f5ff33cc1f695dce
RUN apk add --no-cache libstdc++ libgcc
WORKDIR /app
COPY fm-knext-linux /app/server
COPY .output/public /app/.output/public
COPY .output/server/node_modules /app/.output/server/node_modules
USER 65532:65532
ENV PORT=3000
EXPOSE 3000
CMD ["/app/server"]
