// AUTO-GENERATED by kn-next build - DO NOT EDIT
// Source: kn-next.config.ts
import type { OpenNextConfig } from '@opennextjs/aws/types/open-next';

const config: OpenNextConfig = {
  default: {
    override: {
      // Storage provider: gcs
      incrementalCache: async () => {
        const mod = await import('@kn-next/config/adapters/redis-cache');
        return mod.default;
      },

      // Cache provider: redis
      tagCache: async () => {
        const mod = await import('@kn-next/config/adapters/redis-tag-cache');
        return mod.default;
      },

      // Queue provider: kafka
      queue: async () => {
        const mod = await import('@kn-next/config/adapters/kafka-queue');
        return mod.default;
      },

      // Use Node.js converter for HTTP requests (not Lambda/API Gateway)
      converter: 'node',

      // Use Node.js wrapper for Knative (not Lambda)
      wrapper: async () => {
        const mod = await import('@kn-next/config/adapters/node-server');
        return mod.default;
      },
    },
  },
};

export default config;
