import { writeFileSync } from "node:fs";
import { join } from "node:path";
import YAML from "yaml";
import type {
	KnativeNextConfig,
	MinioInfraConfig,
	ObservabilityConfig,
	PostgresConfig,
	RedisInfraConfig,
} from "../config";

/**
 * Generates Kubernetes/Knative manifests for infrastructure services.
 * Uses structured YAML objects — no string templates.
 */

export interface InfrastructureOutput {
	manifests: string[];
	envVars: Record<string, string>;
}

function toYaml(docs: Record<string, unknown>[], header: string): string {
	return docs
		.map((doc) => `# ${header}\n# Generated by kn-next CLI\n${YAML.stringify(doc)}`)
		.join("---\n");
}

export function generateInfrastructure(
	config: KnativeNextConfig,
	outputDir: string,
): InfrastructureOutput {
	const manifests: string[] = [];
	const envVars: Record<string, string> = {};
	const namespace = "default";

	const infra = config.infrastructure;

	// PostgreSQL
	if (infra?.postgres?.enabled) {
		const pgDocs = generatePostgresDocs(config.name, infra.postgres);
		const pgPath = join(outputDir, "postgres.yaml");
		writeFileSync(pgPath, toYaml(pgDocs, `PostgreSQL for ${config.name}`));
		manifests.push(pgPath);

		const pgHost = `${config.name}-postgres.${namespace}.svc.cluster.local`;
		envVars.DATABASE_URL = `postgres://postgres:$(POSTGRES_PASSWORD)@${pgHost}:5432/app`;
		console.info(`[kn-next] Generated ${pgPath}`);
	}

	// Redis
	if (infra?.redis?.enabled) {
		const redisDocs = generateRedisDocs(config.name, infra.redis);
		const redisPath = join(outputDir, "redis.yaml");
		writeFileSync(redisPath, toYaml(redisDocs, `Redis for ${config.name}`));
		manifests.push(redisPath);

		const redisHost = `${config.name}-redis.${namespace}.svc.cluster.local`;
		envVars.REDIS_URL = `redis://${redisHost}:6379`;
		console.info(`[kn-next] Generated ${redisPath}`);
	}

	// MinIO
	if (infra?.minio?.enabled) {
		const minioDocs = generateMinioDocs(config.name, infra.minio);
		const minioPath = join(outputDir, "minio.yaml");
		writeFileSync(minioPath, toYaml(minioDocs, `MinIO for ${config.name}`));
		manifests.push(minioPath);

		const minioHost = `${config.name}-minio.${namespace}.svc.cluster.local`;
		envVars.MINIO_ENDPOINT = `http://${minioHost}:9000`;
		console.info(`[kn-next] Generated ${minioPath}`);
	}

	// Observability (Prometheus + Grafana)
	if (config.observability?.enabled) {
		const obsManifest = generateObservabilityManifest(
			config.name,
			config.observability,
		);
		const obsPath = join(outputDir, "observability.yaml");
		writeFileSync(obsPath, obsManifest);
		manifests.push(obsPath);
		console.info(`[kn-next] Generated ${obsPath}`);
	}

	return { manifests, envVars };
}

/**
 * Fix #7: PostgreSQL credentials stored in a K8s Secret, referenced via secretKeyRef.
 * No more hardcoded passwords in generated manifests.
 */
function generatePostgresDocs(
	appName: string,
	config: PostgresConfig,
): Record<string, unknown>[] {
	const version = config.version ?? "16";
	const storage = config.storage ?? "1Gi";
	const secretName = `${appName}-postgres-credentials`;

	return [
		// Secret with base64 credentials
		{
			apiVersion: "v1",
			kind: "Secret",
			metadata: {
				name: secretName,
				labels: { app: `${appName}-postgres`, "generated-by": "kn-next" },
			},
			type: "Opaque",
			stringData: {
				POSTGRES_USER: "postgres",
				POSTGRES_PASSWORD: "postgres",
				POSTGRES_DB: "app",
			},
		},
		// Headless Service
		{
			apiVersion: "v1",
			kind: "Service",
			metadata: {
				name: `${appName}-postgres`,
				labels: { app: `${appName}-postgres` },
			},
			spec: {
				ports: [{ port: 5432, targetPort: 5432 }],
				selector: { app: `${appName}-postgres` },
				clusterIP: "None",
			},
		},
		// StatefulSet referencing the Secret
		{
			apiVersion: "apps/v1",
			kind: "StatefulSet",
			metadata: { name: `${appName}-postgres` },
			spec: {
				serviceName: `${appName}-postgres`,
				replicas: 1,
				selector: { matchLabels: { app: `${appName}-postgres` } },
				template: {
					metadata: { labels: { app: `${appName}-postgres` } },
					spec: {
						containers: [
							{
								name: "postgres",
								image: `postgres:${version}-alpine`,
								ports: [{ containerPort: 5432 }],
								envFrom: [{ secretRef: { name: secretName } }],
								env: [
									{
										name: "PGDATA",
										value: "/var/lib/postgresql/data/pgdata",
									},
								],
								volumeMounts: [
									{
										name: "postgres-data",
										mountPath: "/var/lib/postgresql/data",
									},
								],
							},
						],
					},
				},
				volumeClaimTemplates: [
					{
						metadata: { name: "postgres-data" },
						spec: {
							accessModes: ["ReadWriteOnce"],
							resources: { requests: { storage } },
						},
					},
				],
			},
		},
	];
}

function generateRedisDocs(
	appName: string,
	config: RedisInfraConfig,
): Record<string, unknown>[] {
	const version = config.version ?? "7";

	return [
		{
			apiVersion: "v1",
			kind: "Service",
			metadata: {
				name: `${appName}-redis`,
				labels: { app: `${appName}-redis` },
			},
			spec: {
				ports: [{ port: 6379, targetPort: 6379 }],
				selector: { app: `${appName}-redis` },
			},
		},
		{
			apiVersion: "apps/v1",
			kind: "Deployment",
			metadata: { name: `${appName}-redis` },
			spec: {
				replicas: 1,
				selector: { matchLabels: { app: `${appName}-redis` } },
				template: {
					metadata: { labels: { app: `${appName}-redis` } },
					spec: {
						containers: [
							{
								name: "redis",
								image: `redis:${version}-alpine`,
								ports: [{ containerPort: 6379 }],
								args: ["redis-server", "--appendonly", "yes"],
							},
						],
					},
				},
			},
		},
	];
}

function generateMinioDocs(
	appName: string,
	config: MinioInfraConfig,
): Record<string, unknown>[] {
	const storage = config.storage ?? "10Gi";
	const secretName = `${appName}-minio-credentials`;

	return [
		// Secret for MinIO credentials
		{
			apiVersion: "v1",
			kind: "Secret",
			metadata: {
				name: secretName,
				labels: { app: `${appName}-minio`, "generated-by": "kn-next" },
			},
			type: "Opaque",
			stringData: {
				MINIO_ROOT_USER: config.accessKey ?? "minioadmin",
				MINIO_ROOT_PASSWORD: config.secretKey ?? "minioadmin",
			},
		},
		{
			apiVersion: "v1",
			kind: "Service",
			metadata: {
				name: `${appName}-minio`,
				labels: { app: `${appName}-minio` },
			},
			spec: {
				ports: [
					{ port: 9000, targetPort: 9000, name: "api" },
					{ port: 9001, targetPort: 9001, name: "console" },
				],
				selector: { app: `${appName}-minio` },
			},
		},
		{
			apiVersion: "apps/v1",
			kind: "StatefulSet",
			metadata: { name: `${appName}-minio` },
			spec: {
				serviceName: `${appName}-minio`,
				replicas: 1,
				selector: { matchLabels: { app: `${appName}-minio` } },
				template: {
					metadata: { labels: { app: `${appName}-minio` } },
					spec: {
						containers: [
							{
								name: "minio",
								image: "minio/minio:latest",
								args: ["server", "/data", "--console-address", ":9001"],
								ports: [
									{ containerPort: 9000 },
									{ containerPort: 9001 },
								],
								envFrom: [{ secretRef: { name: secretName } }],
								volumeMounts: [
									{ name: "minio-data", mountPath: "/data" },
								],
							},
						],
					},
				},
				volumeClaimTemplates: [
					{
						metadata: { name: "minio-data" },
						spec: {
							accessModes: ["ReadWriteOnce"],
							resources: { requests: { storage } },
						},
					},
				],
			},
		},
	];
}

/**
 * Generates observability resources: ServiceMonitor + Grafana dashboard ConfigMap.
 */
export function generateObservabilityManifest(
	appName: string,
	config: ObservabilityConfig,
): string {
	const scrapeInterval = config.prometheus?.scrapeInterval ?? "15s";
	const grafanaEnabled = config.grafana?.enabled !== false;

	const docs: Record<string, unknown>[] = [
		{
			apiVersion: "monitoring.coreos.com/v1",
			kind: "ServiceMonitor",
			metadata: {
				name: `${appName}-metrics`,
				labels: { app: appName, "generated-by": "kn-next" },
			},
			spec: {
				selector: {
					matchLabels: {
						"serving.knative.dev/service": appName,
					},
				},
				endpoints: [
					{ port: "http", path: "/metrics", interval: scrapeInterval },
				],
			},
		},
	];

	if (grafanaEnabled) {
		const dashboardJson = generateDashboardJson(appName);
		docs.push({
			apiVersion: "v1",
			kind: "ConfigMap",
			metadata: {
				name: `${appName}-grafana-dashboard`,
				labels: {
					app: appName,
					"generated-by": "kn-next",
					grafana_dashboard: "1",
				},
			},
			data: {
				[`${appName}-bytecode.json`]: dashboardJson,
			},
		});
	}

	return toYaml(docs, `Observability resources for ${appName}`);
}

function generateDashboardJson(appName: string): string {
	const dashboard = {
		annotations: { list: [] },
		editable: true,
		panels: [
			{
				title: "🚀 Cold Start Duration",
				type: "timeseries",
				gridPos: { h: 8, w: 12, x: 0, y: 0 },
				targets: [
					{
						expr: `histogram_quantile(0.95, rate(kn_next_startup_duration_seconds_bucket{app="${appName}"}[$__rate_interval]))`,
						legendFormat: "p95 ({{cache_status}})",
					},
					{
						expr: `histogram_quantile(0.50, rate(kn_next_startup_duration_seconds_bucket{app="${appName}"}[$__rate_interval]))`,
						legendFormat: "p50 ({{cache_status}})",
					},
				],
				fieldConfig: { defaults: { unit: "s" } },
			},
			{
				title: "🔥 Warm vs ❄️ Cold Starts",
				type: "piechart",
				gridPos: { h: 8, w: 6, x: 12, y: 0 },
				targets: [
					{
						expr: `count(kn_next_bytecode_cache_warm_start{app="${appName}"} == 1)`,
						legendFormat: "warm",
					},
					{
						expr: `count(kn_next_bytecode_cache_warm_start{app="${appName}"} == 0)`,
						legendFormat: "cold",
					},
				],
			},
			{
				title: "📁 Cached Files",
				type: "stat",
				gridPos: { h: 4, w: 6, x: 0, y: 8 },
				targets: [
					{
						expr: `kn_next_bytecode_cache_files_total{app="${appName}"}`,
						legendFormat: "{{build_id}}",
					},
				],
			},
			{
				title: "💾 Cache Size",
				type: "stat",
				gridPos: { h: 4, w: 6, x: 6, y: 8 },
				targets: [
					{
						expr: `kn_next_bytecode_cache_size_bytes{app="${appName}"}`,
						legendFormat: "{{build_id}}",
					},
				],
				fieldConfig: { defaults: { unit: "bytes" } },
			},
		],
		refresh: "10s",
		schemaVersion: 39,
		tags: ["kn-next", "bytecode", appName],
		title: `kn-next: ${appName} Bytecode Cache`,
		uid: `kn-next-${appName}`,
		version: 1,
	};

	return JSON.stringify(dashboard, null, 2);
}
