import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type {
  KnativeNextConfig,
  MinioInfraConfig,
  PostgresConfig,
  RedisInfraConfig,
} from '../config';

/**
 * Generates Kubernetes/Knative manifests for infrastructure services
 */

export interface InfrastructureOutput {
  manifests: string[];
  envVars: Record<string, string>;
}

export function generateInfrastructure(
  config: KnativeNextConfig,
  outputDir: string,
): InfrastructureOutput {
  const infra = config.infrastructure;
  if (!infra) {
    return { manifests: [], envVars: {} };
  }

  const manifests: string[] = [];
  const envVars: Record<string, string> = {};
  const namespace = 'default';

  // PostgreSQL
  if (infra.postgres?.enabled) {
    const pgManifest = generatePostgresManifest(config.name, infra.postgres);
    const pgPath = join(outputDir, 'postgres.yaml');
    writeFileSync(pgPath, pgManifest);
    manifests.push(pgPath);

    const pgHost = `${config.name}-postgres.${namespace}.svc.cluster.local`;
    envVars.DATABASE_URL = `postgres://postgres:postgres@${pgHost}:5432/app`;
    console.log(`[kn-next] Generated ${pgPath}`);
  }

  // Redis
  if (infra.redis?.enabled) {
    const redisManifest = generateRedisManifest(config.name, infra.redis);
    const redisPath = join(outputDir, 'redis.yaml');
    writeFileSync(redisPath, redisManifest);
    manifests.push(redisPath);

    const redisHost = `${config.name}-redis.${namespace}.svc.cluster.local`;
    envVars.REDIS_URL = `redis://${redisHost}:6379`;
    console.log(`[kn-next] Generated ${redisPath}`);
  }

  // MinIO
  if (infra.minio?.enabled) {
    const minioManifest = generateMinioManifest(config.name, infra.minio);
    const minioPath = join(outputDir, 'minio.yaml');
    writeFileSync(minioPath, minioManifest);
    manifests.push(minioPath);

    const minioHost = `${config.name}-minio.${namespace}.svc.cluster.local`;
    envVars.MINIO_ENDPOINT = `http://${minioHost}:9000`;
    envVars.MINIO_ACCESS_KEY = infra.minio.accessKey ?? 'minioadmin';
    envVars.MINIO_SECRET_KEY = infra.minio.secretKey ?? 'minioadmin';
    console.log(`[kn-next] Generated ${minioPath}`);
  }

  return { manifests, envVars };
}

function generatePostgresManifest(appName: string, config: PostgresConfig): string {
  const version = config.version ?? '16';
  const storage = config.storage ?? '1Gi';

  return `# PostgreSQL StatefulSet for ${appName}
# Generated by kn-next CLI
apiVersion: v1
kind: Service
metadata:
  name: ${appName}-postgres
  labels:
    app: ${appName}-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: ${appName}-postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${appName}-postgres
spec:
  serviceName: ${appName}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: ${appName}-postgres
  template:
    metadata:
      labels:
        app: ${appName}-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:${version}-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: app
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: ${storage}
`;
}

function generateRedisManifest(appName: string, config: RedisInfraConfig): string {
  const version = config.version ?? '7';

  return `# Redis Deployment for ${appName}
# Generated by kn-next CLI
apiVersion: v1
kind: Service
metadata:
  name: ${appName}-redis
  labels:
    app: ${appName}-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: ${appName}-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${appName}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${appName}-redis
  template:
    metadata:
      labels:
        app: ${appName}-redis
    spec:
      containers:
        - name: redis
          image: redis:${version}-alpine
          ports:
            - containerPort: 6379
          args:
            - redis-server
            - --appendonly
            - "yes"
`;
}

function generateMinioManifest(appName: string, config: MinioInfraConfig): string {
  const storage = config.storage ?? '10Gi';
  const accessKey = config.accessKey ?? 'minioadmin';
  const secretKey = config.secretKey ?? 'minioadmin';

  return `# MinIO StatefulSet for ${appName}
# Generated by kn-next CLI
apiVersion: v1
kind: Service
metadata:
  name: ${appName}-minio
  labels:
    app: ${appName}-minio
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: api
    - port: 9001
      targetPort: 9001
      name: console
  selector:
    app: ${appName}-minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${appName}-minio
spec:
  serviceName: ${appName}-minio
  replicas: 1
  selector:
    matchLabels:
      app: ${appName}-minio
  template:
    metadata:
      labels:
        app: ${appName}-minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              value: "${accessKey}"
            - name: MINIO_ROOT_PASSWORD
              value: "${secretKey}"
          volumeMounts:
            - name: minio-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: minio-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: ${storage}
`;
}
