import { writeFileSync } from 'node:fs';
import path from 'node:path';
import type { KnativeNextConfig } from '../config';
import { getRequiredEnvVars } from './open-next-config';

export interface GenerateKnativeManifestOptions {
  config: KnativeNextConfig;
  outputDir: string;
  imageTag?: string;
  namespace?: string;
  enableKafkaQueue?: boolean;
  additionalEnvVars?: Record<string, string>; // Infrastructure connection vars
}

/**
 * Generates Knative Service manifest from kn-next.config.ts.
 * Includes all required environment variables for the adapters.
 */
export function generateKnativeManifest(options: GenerateKnativeManifestOptions): string {
  const {
    config,
    outputDir,
    imageTag = 'latest',
    namespace = 'default',
    enableKafkaQueue = false,
    additionalEnvVars = {},
  } = options;

  const envVars = { ...getRequiredEnvVars(config), ...additionalEnvVars };

  // Add Kafka env vars if enabled
  if (enableKafkaQueue) {
    envVars.KAFKA_BROKER_URL = '${KAFKA_BROKER_URL}';
    envVars.KAFKA_REVALIDATION_TOPIC = `${config.name}-revalidation`;
  }

  // Format env vars for YAML (12-space indent for env array items)
  const envVarsYaml = Object.entries(envVars)
    .map(([key, value]) => `            - name: ${key}\n              value: "${value}"`)
    .join('\n');

  const manifest = `# AUTO-GENERATED by kn-next build - DO NOT EDIT
# Source: kn-next.config.ts
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${config.name}
  namespace: ${namespace}
  labels:
    app: ${config.name}
    generated-by: kn-next
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "${config.scaling?.minScale ?? 0}"
        autoscaling.knative.dev/max-scale: "${config.scaling?.maxScale ?? 10}"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
        - image: ${config.registry}/${config.name}:${imageTag}
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
${envVarsYaml}
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
`;

  const outputPath = path.join(outputDir, 'knative-service.yaml');
  writeFileSync(outputPath, manifest, 'utf-8');

  console.log(`[kn-next] Generated ${outputPath}`);
  return outputPath;
}

/**
 * Generates Knative Eventing resources for ISR revalidation via Kafka.
 */
export function generateKafkaEventingManifest(options: {
  config: KnativeNextConfig;
  outputDir: string;
  kafkaBroker: string;
}): string {
  const { config, outputDir, kafkaBroker } = options;
  const topic = `${config.name}-revalidation`;

  const manifest = `# AUTO-GENERATED by kn-next build - DO NOT EDIT
# Knative Eventing configuration for ISR revalidation
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: ${config.name}-revalidation-source
spec:
  consumerGroup: ${config.name}-revalidation
  bootstrapServers:
    - ${kafkaBroker}
  topics:
    - ${topic}
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: ${config.name}-revalidator
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${config.name}-revalidator
spec:
  template:
    spec:
      containers:
        - image: ${config.registry}/${config.name}-revalidator:latest
          env:
            - name: TARGET_HOST
              value: "${config.name}.default.svc.cluster.local"
`;

  const outputPath = path.join(outputDir, 'knative-eventing.yaml');
  writeFileSync(outputPath, manifest, 'utf-8');

  console.log(`[kn-next] Generated ${outputPath}`);
  return outputPath;
}
