/**
 * @generated GENERATED FILE — do not edit by hand.
 * Source of truth: packages/kn-next/src/cli/cr-builder.ts (scanned).
 * Regenerate: bun scripts/gen-cr-fields.ts
 *
 * Every NextApp CR field path `buildNextAppCRObject` can emit. Derived by
 * SCANNING the builder (never enumerated) so it cannot silently go stale; the
 * scan lives in extract-emitted-fields.ts and the staleness gate in
 * cr-fields-generated.test.ts.
 *
 * `*` = a dynamic map key or an array index.
 */

export const EMITTED_CR_FIELD_PATHS: readonly string[] = [
    "apiVersion",
    "kind",
    "metadata",
    "metadata.name",
    "metadata.namespace",
    "spec",
    "spec.buildId",
    "spec.cache",
    "spec.cache.keyPrefix",
    "spec.cache.provider",
    "spec.cache.url",
    "spec.database",
    "spec.database.roSecretRef",
    "spec.database.roSecretRef.key",
    "spec.database.roSecretRef.name",
    "spec.database.secretRef",
    "spec.database.secretRef.key",
    "spec.database.secretRef.name",
    "spec.env",
    "spec.healthCheckPath",
    "spec.image",
    "spec.observability",
    "spec.observability.enabled",
    "spec.observability.rum",
    "spec.observability.rum.enabled",
    "spec.observability.rum.sampleRate",
    "spec.observability.tracing",
    "spec.observability.tracing.enabled",
    "spec.observability.tracing.endpoint",
    "spec.observability.tracing.sampleRate",
    "spec.preview",
    "spec.preview.branch",
    "spec.preview.enabled",
    "spec.preview.prId",
    "spec.resources",
    "spec.resources.cpuLimit",
    "spec.resources.cpuRequest",
    "spec.resources.memoryLimit",
    "spec.resources.memoryRequest",
    "spec.revalidation",
    "spec.revalidation.kafkaBrokerUrl",
    "spec.revalidation.queue",
    "spec.runtime",
    "spec.scaling",
    "spec.scaling.containerConcurrency",
    "spec.scaling.imagePrewarm",
    "spec.scaling.maxScale",
    "spec.scaling.minScale",
    "spec.scaling.panicThresholdPercentage",
    "spec.scaling.panicWindowPercentage",
    "spec.scaling.poolMax",
    "spec.scaling.targetBurstCapacity",
    "spec.scaling.warmSchedule",
    "spec.scaling.warmSchedule.*.end",
    "spec.scaling.warmSchedule.*.replicas",
    "spec.scaling.warmSchedule.*.start",
    "spec.scaling.warmSchedule.*.timezone",
    "spec.secrets",
    "spec.secrets.envFrom",
    "spec.secrets.envMap",
    "spec.secrets.envMap.*.secretKey",
    "spec.secrets.envMap.*.secretName",
    "spec.storage",
    "spec.storage.bucket",
    "spec.storage.endpoint",
    "spec.storage.provider",
    "spec.storage.region",
];
