import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import type { KnativeNextConfig } from "../config";
import {
    generateOpenNextConfig,
    getRequiredEnvVars,
} from "../generators/open-next-config";

describe("OpenNext Config Generator", () => {
    let tempDir: string;

    beforeEach(() => {
        tempDir = mkdtempSync(join(tmpdir(), "kn-next-test-"));
    });

    afterEach(() => {
        rmSync(tempDir, { recursive: true, force: true });
    });

    it("should generate config file with GCS storage provider", () => {
        const config: KnativeNextConfig = {
            name: "test-app",
            storage: {
                provider: "gcs",
                bucket: "test-bucket",
                publicUrl: "https://storage.googleapis.com/test-bucket",
            },
            registry: "gcr.io/test-project",
        };

        const outputPath = generateOpenNextConfig({
            config,
            outputDir: tempDir,
        });

        expect(existsSync(outputPath)).toBe(true);

        const content = readFileSync(outputPath, "utf-8");
        expect(content).toContain("AUTO-GENERATED by kn-next");
        expect(content).toContain("gcs-cache");
    });

    it("should generate config file with Redis cache provider", () => {
        const config: KnativeNextConfig = {
            name: "test-app",
            storage: {
                provider: "gcs",
                bucket: "test-bucket",
                publicUrl: "https://storage.googleapis.com/test-bucket",
            },
            cache: {
                provider: "redis",
                url: "redis://localhost:6379",
            },
            registry: "gcr.io/test-project",
        };

        const outputPath = generateOpenNextConfig({
            config,
            outputDir: tempDir,
        });

        const content = readFileSync(outputPath, "utf-8");
        expect(content).toContain("redis-tag-cache");
    });

    it("should include Kafka queue when enabled", () => {
        const config: KnativeNextConfig = {
            name: "test-app",
            storage: {
                provider: "gcs",
                bucket: "test-bucket",
                publicUrl: "https://storage.googleapis.com/test-bucket",
            },
            registry: "gcr.io/test-project",
        };

        const outputPath = generateOpenNextConfig({
            config,
            outputDir: tempDir,
            enableKafkaQueue: true,
        });

        const content = readFileSync(outputPath, "utf-8");
        expect(content).toContain("kafka-queue");
    });

    describe("getRequiredEnvVars", () => {
        it("should return GCS env vars for GCS provider", () => {
            const config: KnativeNextConfig = {
                name: "test-app",
                storage: {
                    provider: "gcs",
                    bucket: "my-bucket",
                    publicUrl: "https://storage.googleapis.com/my-bucket",
                },
                registry: "gcr.io/test-project",
            };

            const envVars = getRequiredEnvVars(config);

            expect(envVars.GCS_BUCKET_NAME).toBe("my-bucket");
        });

        it("should return Redis env vars for Redis cache", () => {
            const config: KnativeNextConfig = {
                name: "test-app",
                storage: {
                    provider: "gcs",
                    bucket: "my-bucket",
                    publicUrl: "https://storage.googleapis.com/my-bucket",
                },
                cache: {
                    provider: "redis",
                    url: "redis://redis:6379",
                },
                registry: "gcr.io/test-project",
            };

            const envVars = getRequiredEnvVars(config);

            expect(envVars.REDIS_URL).toBe("redis://redis:6379");
        });

        it("should return S3 env vars for MinIO provider", () => {
            const config: KnativeNextConfig = {
                name: "test-app",
                storage: {
                    provider: "minio",
                    bucket: "my-bucket",
                    publicUrl: "http://minio:9000/my-bucket",
                    region: "us-east-1",
                    endpoint: "http://minio:9000",
                },
                registry: "docker.io/myrepo",
            };

            const envVars = getRequiredEnvVars(config);

            expect(envVars.CACHE_BUCKET_NAME).toBe("my-bucket");
            expect(envVars.S3_ENDPOINT).toBe("http://minio:9000");
        });
    });
});
