/**
 * vinext-compile bundles the packages nitro's server output reaches through
 * rolldown's `createRequire(import.meta.url)` require, in EVERY shape rolldown
 * emits (#1314, and the #1309 entry case).
 *
 * The fixtures are generated by the REAL rolldown the toolchain locks (never
 * hand-written: the first version of this fix matched a shape rolldown does
 * not emit and was a silent no-op). rolldown 1.2.6 emits:
 *   - unminified: `var __require = /* #__PURE__ *\/ (() => createRequire(import.meta.url))();`
 *   - minified:   `import{createRequire as e}from"node:module";…u=e(import.meta.url)`
 *   - with >1 CommonJS chunk, the binding is hoisted into
 *     `chunks/rolldown-runtime.mjs` and the other chunks import it
 *     (`import { n as __require } from "./rolldown-runtime.mjs"`), so the calls
 *     live in a DIFFERENT module than the binding.
 *
 * Every binary is deployed to a DIFFERENT directory than it was compiled in,
 * without `.output/server/node_modules`, so build-time paths and the sidecar
 * cannot mask a missing bundle.
 */

import { afterAll, describe, expect, it } from "bun:test";
import { spawnSync } from "node:child_process";
import {
    cpSync,
    existsSync,
    mkdirSync,
    mkdtempSync,
    readFileSync,
    realpathSync,
    rmSync,
    writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

// The rolldown vinext itself builds with (the locked toolchain), reached through
// vinext's own dependency tree: @getknext/core depends on vinext, not rolldown.
const vinextRequire = createRequire(require.resolve("vinext/package.json"));
const { rolldown, VERSION: ROLLDOWN_VERSION } = (await import(
    pathToFileURL(vinextRequire.resolve("rolldown")).href
)) as typeof import("rolldown");

const COMPILE = resolve(import.meta.dir, "../adapters/vinext-compile.mjs");
const A = "KNEXT_1314_DEP_A_MARKER_3f7a";
const B = "KNEXT_1314_DEP_B_MARKER_8e21";
const LIVE = "KNEXT_1314_DEP_A_LIVE_SIDECAR_c91e";
const MISSING = "knext-1314-not-installed";

const temps: string[] = [];
afterAll(() => {
    for (const d of temps) rmSync(d, { recursive: true, force: true });
});
function temp(prefix: string): string {
    // realpath: macOS tmpdir is a /var -> /private/var symlink, and
    // vinext-compile matches server modules by resolved path.
    const d = realpathSync(mkdtempSync(join(tmpdir(), prefix)));
    temps.push(d);
    return d;
}
function write(path: string, body: string): void {
    mkdirSync(resolve(path, ".."), { recursive: true });
    writeFileSync(path, body);
}
function cjsPackage(nm: string, name: string, body: string): void {
    write(
        join(nm, name, "package.json"),
        JSON.stringify({ name, version: "1.0.0", main: "lib/main.js" }),
    );
    write(join(nm, name, "lib", "main.js"), body);
}

type Shape = {
    multi: boolean;
    minify: boolean;
    missing?: boolean;
    dynamic?: boolean;
};

/**
 * Build a nitro-shaped `.output/server` with real rolldown: CommonJS modules
 * that `require()` packages left external, emitted as ESM for node.
 */
async function rolldownOutput(
    shape: Shape,
): Promise<{ work: string; server: string }> {
    const work = temp("knext-1314-");
    const src = join(work, "src");
    write(join(src, "a.cjs"), 'module.exports = () => require("dep-a");\n');
    write(join(src, "b.cjs"), 'module.exports = () => require("dep-b");\n');
    write(
        join(src, "m.cjs"),
        `module.exports = () => { try { return require("${MISSING}"); } catch { return "absent"; } };\n`,
    );
    // `require(name)`: rolldown emits `__require(name)`, a specifier known only
    // at runtime.
    write(join(src, "d.cjs"), "module.exports = (name) => require(name);\n");
    const missingUse =
        (shape.missing ? '+ ":" + (await import("./cm.mjs")).default()' : "") +
        (shape.dynamic
            ? '+ ":" + typeof (await import("./cd.mjs")).default'
            : "");
    if (shape.multi) {
        // Dynamic imports force separate chunks, so rolldown hoists the
        // require binding into chunks/rolldown-runtime.mjs.
        write(
            join(src, "ca.mjs"),
            'import a from "./a.cjs"; export default a;\n',
        );
        write(
            join(src, "cb.mjs"),
            'import b from "./b.cjs"; export default b;\n',
        );
        write(
            join(src, "cm.mjs"),
            'import m from "./m.cjs"; export default m;\n',
        );
        write(
            join(src, "cd.mjs"),
            'import d from "./d.cjs"; export default d;\n',
        );
        write(
            join(src, "index.mjs"),
            "(async () => {\n" +
                '  const out = (await import("./ca.mjs")).default() + "+" + (await import("./cb.mjs")).default()' +
                `${missingUse};\n` +
                '  console.log("RESULT:" + out);\n' +
                "})();\n",
        );
    } else {
        write(
            join(src, "index.mjs"),
            'import a from "./a.cjs"; import b from "./b.cjs";\n' +
                (shape.missing ? 'import m from "./m.cjs";\n' : "") +
                (shape.dynamic
                    ? 'import d from "./d.cjs";\nglobalThis.d = d;\n'
                    : "") +
                `console.log("RESULT:" + a() + "+" + b()${shape.missing ? ' + ":" + m()' : ""});\n`,
        );
    }
    const server = join(work, ".output", "server");
    const bundle = await rolldown({
        input: join(src, "index.mjs"),
        platform: "node",
        external: ["dep-a", "dep-b", MISSING],
    });
    await bundle.write({
        dir: server,
        format: "esm",
        minify: shape.minify,
        entryFileNames: "index.mjs",
        chunkFileNames: "chunks/[name].mjs",
    });
    // Guard against fixture drift: the shapes under test must really be there.
    const runtime = join(server, "chunks", "rolldown-runtime.mjs");
    expect(existsSync(runtime)).toBe(shape.multi);
    const binding = readFileSync(
        shape.multi ? runtime : join(server, "index.mjs"),
        "utf8",
    );
    expect(binding).toMatch(
        shape.minify
            ? /import\{createRequire as \w+\}from"node:module"/
            : /\(\(\) => createRequire\(import\.meta\.url\)\)\(\)/,
    );
    // nitro traces the externals into .output/server/node_modules.
    const nm = join(server, "node_modules");
    cjsPackage(nm, "dep-a", `module.exports = ${JSON.stringify(A)};\n`);
    cjsPackage(nm, "dep-b", `module.exports = ${JSON.stringify(B)};\n`);
    write(
        join(work, "package.json"),
        JSON.stringify({ name: "app", private: true, type: "module" }),
    );
    return { work, server };
}

function compile(
    work: string,
    server: string,
    env: Record<string, string> = {},
): ReturnType<typeof spawnSync> & { exe: string } {
    const exe = join(work, "knext-1314-exec");
    const r = spawnSync(
        process.execPath,
        [COMPILE, "--entry", join(server, "index.mjs"), "--outfile", exe],
        { cwd: work, encoding: "utf8", env: { ...process.env, ...env } },
    );
    return Object.assign(r, { exe });
}

/** Copy the binary (and optionally the sidecar) elsewhere and run it. */
function deployAndRun(
    work: string,
    exe: string,
    withSidecar = false,
): ReturnType<typeof spawnSync> {
    const deployed = temp("knext-1314-deploy-");
    const target = join(deployed, "server");
    cpSync(exe, target);
    if (withSidecar) {
        const nm = join(deployed, ".output", "server", "node_modules");
        cpSync(join(work, ".output", "server", "node_modules"), nm, {
            recursive: true,
        });
        // Only a load from the deployed sidecar can print LIVE.
        write(
            join(nm, "dep-a", "lib", "main.js"),
            `module.exports = ${JSON.stringify(LIVE)};\n`,
        );
    }
    return spawnSync(target, [], {
        cwd: deployed,
        encoding: "utf8",
        timeout: 60_000,
    });
}

const SHAPES: [string, Shape][] = [
    ["single chunk", { multi: false, minify: false }],
    ["single chunk, minified", { multi: false, minify: true }],
    [
        "multi chunk (hoisted rolldown-runtime binding)",
        { multi: true, minify: false },
    ],
    ["multi chunk, minified", { multi: true, minify: true }],
];

describe(`vinext-compile bundles rolldown ${ROLLDOWN_VERSION}'s createRequire externals (#1309, #1314)`, () => {
    for (const [label, shape] of SHAPES) {
        it(`${label}: the deployed binary loads the externals with no node_modules beside it`, async () => {
            const { work, server } = await rolldownOutput(shape);
            const build = compile(work, server);
            expect(build.status, `${build.stdout}\n${build.stderr}`).toBe(0);
            expect(build.stdout).toContain("dep-a (");
            expect(build.stdout).toContain("dep-b (");

            const run = deployAndRun(work, build.exe);
            expect(run.status, `${run.stdout}\n${run.stderr}`).toBe(0);
            expect(run.stdout).toContain(`RESULT:${A}+${B}`);
        }, 120_000);
    }

    it("multi chunk: a CommonJS external loads from the sidecar when it is deployed beside the binary", async () => {
        const { work, server } = await rolldownOutput({
            multi: true,
            minify: false,
        });
        const build = compile(work, server);
        expect(build.status, `${build.stdout}\n${build.stderr}`).toBe(0);

        const run = deployAndRun(work, build.exe, true);
        expect(run.status, `${run.stdout}\n${run.stderr}`).toBe(0);
        expect(run.stdout).toContain(`RESULT:${LIVE}+${B}`);
    }, 120_000);

    for (const minify of [false, true]) {
        const tag = minify ? ", minified" : "";
        it(`multi chunk${tag}: warns, naming the chunk, when a required package cannot be bundled`, async () => {
            const { work, server } = await rolldownOutput({
                multi: true,
                minify,
                missing: true,
            });
            const build = compile(work, server);
            expect(build.status, `${build.stdout}\n${build.stderr}`).toBe(0);
            expect(build.stderr).toContain(`${MISSING} (chunks/`);

            // The optional require still behaves as before: it throws only if run.
            const run = deployAndRun(work, build.exe);
            expect(run.status, `${run.stdout}\n${run.stderr}`).toBe(0);
            expect(run.stdout).toContain(`RESULT:${A}+${B}:absent`);
        }, 120_000);

        it(`multi chunk${tag}: fails the build under KNEXT_COMPILE_STRICT_REQUIRES=1`, async () => {
            const { work, server } = await rolldownOutput({
                multi: true,
                minify,
                missing: true,
            });
            const build = compile(work, server, {
                KNEXT_COMPILE_STRICT_REQUIRES: "1",
            });
            expect(build.status).not.toBe(0);
            expect(build.stderr).toContain(`${MISSING} (chunks/`);
            expect(build.stderr).toContain("KNEXT_COMPILE_STRICT_REQUIRES=1");
        }, 120_000);
    }

    for (const [label, shape] of [
        ["multi chunk", { multi: true, minify: false, dynamic: true }],
        ["multi chunk, minified", { multi: true, minify: true, dynamic: true }],
        [
            "single chunk, minified",
            { multi: false, minify: true, dynamic: true },
        ],
    ] as [string, Shape][]) {
        it(`${label}: warns, naming the module, on a require with a non-literal package name`, async () => {
            const { work, server } = await rolldownOutput(shape);
            const build = compile(work, server);
            expect(build.status, `${build.stdout}\n${build.stderr}`).toBe(0);
            expect(build.stderr).toContain(
                "runtime require called with a non-literal package name",
            );
            expect(build.stderr).toContain(
                shape.multi ? "chunks/" : "index.mjs",
            );
        }, 120_000);

        it(`${label}: fails the build on it under KNEXT_COMPILE_STRICT_REQUIRES=1`, async () => {
            const { work, server } = await rolldownOutput(shape);
            const build = compile(work, server, {
                KNEXT_COMPILE_STRICT_REQUIRES: "1",
            });
            expect(build.status).not.toBe(0);
            expect(build.stderr).toContain(
                "runtime require called with a non-literal package name",
            );
        }, 120_000);
    }

    it("does not flag the literal-only outputs (no false positive on real rolldown shapes)", async () => {
        for (const [, shape] of SHAPES) {
            const { work, server } = await rolldownOutput(shape);
            const build = compile(work, server, {
                KNEXT_COMPILE_STRICT_REQUIRES: "1",
            });
            expect(build.status, `${build.stdout}\n${build.stderr}`).toBe(0);
            expect(build.stderr).not.toContain("non-literal");
        }
    }, 240_000);
});
