#!/bin/sh
# GNU coreutils semantics: the template needs at least three trailing X.
tmpl=
while [ $# -gt 0 ]; do
  case "$1" in
    -t) shift; tmpl="${TMPDIR:-/tmp}/$1" ;;
    -*) ;;
    *) tmpl="$1" ;;
  esac
  shift
done
[ -n "$tmpl" ] || tmpl="${TMPDIR:-/tmp}/tmp.XXXXXXXXXX"
body=$tmpl; n=0
while [ "${body%X}" != "$body" ]; do body="${body%X}"; n=$((n+1)); done
if [ "$n" -lt 3 ]; then
  echo "mktemp: too few X's in template '${tmpl##*/}'" >&2
  exit 1
fi
i=0
while [ -e "$body$$-$i" ]; do i=$((i+1)); done
f="$body$$-$i"
: > "$f"
chmod 600 "$f"
echo "$f"
