/**
 * `knext init-ci` — ADR-0049 stage 1, the client-side setup (#874).
 *
 * Generates the two files a client needs to deploy from their own repository to
 * their own cluster: the workflow, and the RBAC manifest that creates the
 * scoped credential the workflow uses.
 *
 * ## Why generate the RBAC rather than document it
 *
 * The alternative is a docs page saying "create a ServiceAccount and bind this
 * Role". People paste from docs pages, and what they paste when the scoped path
 * is fiddly is `cluster-admin` — which is exactly the credential ADR-0049
 * requires the Action to refuse. Generating a manifest they can read, diff and
 * `kubectl apply` makes the narrow path the easy one, which is the only version
 * of a security control that survives contact with a hurry.
 *
 * It writes files and touches no cluster, like `create` and unlike `deploy`.
 * The client applies the manifest themselves — knext never holds their
 * credentials, which is the whole point of stage 1.
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { CI_ROLE_RULES, renderRoleYaml } from "./credential-scope";

/** Where each generated file lands, relative to the repo root. */
export const WORKFLOW_PATH = ".github/workflows/knext-deploy.yml";
export const RBAC_PATH = "knext-ci-rbac.yaml";

/**
 * The four repository secrets ADR-0049 asks the client for, with the reason
 * each is needed. A user who cannot see why a permission is wanted cannot
 * consent to it, so the reasons ship in the generated file rather than only in
 * a docs page.
 */
export const REQUIRED_SECRETS = [
    {
        name: "KNEXT_KUBECONFIG",
        what: "base64 kubeconfig for the ServiceAccount created by knext-ci-rbac.yaml",
        why: "so the workflow can write the NextApp resource — nothing else",
    },
    {
        name: "KNEXT_NAMESPACE",
        what: "the namespace to deploy into",
        why: "keeps the credential's blast radius to one namespace",
    },
    {
        name: "KNEXT_REGISTRY",
        what: "registry host + namespace, e.g. ghcr.io/acme (the app name is appended)",
        why: "where the built image is pushed; you own it, knext never sees it",
    },
    {
        name: "KNEXT_REGISTRY_TOKEN",
        what: "a push token for that registry",
        why: "as above — omit on GHCR, where the built-in GITHUB_TOKEN suffices",
    },
] as const;

/**
 * The RBAC manifest: ServiceAccount, Role, RoleBinding.
 *
 * The Role body comes from `renderRoleYaml`, which reads `CI_ROLE_RULES` —
 * the same constant the preflight classifier checks against. That is not
 * tidiness: if the generator and the check drifted, every client would hit a
 * refusal on the credential knext itself told them to create.
 */
export function renderRbacManifest(namespace: string): string {
    return [
        "# Generated by `knext init-ci`. Read it before applying it.",
        "#",
        "# This grants CI permission to write ONE kind of object in ONE",
        "# namespace. It cannot delete your app, cannot read your Secrets, and",
        "# cannot create Deployments or Services — the knext operator does all",
        "# of that, from the resource this credential writes.",
        "#",
        "#   kubectl apply -f knext-ci-rbac.yaml",
        "",
        "apiVersion: v1",
        "kind: ServiceAccount",
        "metadata:",
        "  name: knext-deployer",
        `  namespace: ${namespace}`,
        "---",
        renderRoleYaml(namespace).trimEnd(),
        "---",
        "apiVersion: rbac.authorization.k8s.io/v1",
        "kind: RoleBinding",
        "metadata:",
        "  name: knext-deployer",
        `  namespace: ${namespace}`,
        "roleRef:",
        "  apiGroup: rbac.authorization.k8s.io",
        "  kind: Role",
        "  name: knext-deployer",
        "subjects:",
        "  - kind: ServiceAccount",
        "    name: knext-deployer",
        `    namespace: ${namespace}`,
        "",
    ].join("\n");
}

/**
 * The workflow. Thin by construction — it hands off to the composite action,
 * which hands off to the CLI, which emits a CR and stops.
 */
export function renderWorkflow(appDir: string): string {
    const secretDocs = REQUIRED_SECRETS.map(
        (s) =>
            `#   ${s.name.padEnd(21)} ${s.what}\n#   ${" ".repeat(21)} ${s.why}`,
    ).join("\n");

    return `# Generated by \`knext init-ci\`.
#
# Deploys this repository to YOUR cluster on YOUR cloud. knext hosts nothing
# and holds no credentials — everything below runs in your CI, against a
# cluster you control.
#
# Repository secrets this needs (Settings -> Secrets and variables -> Actions):
${secretDocs}
#
# The kubeconfig must belong to the ServiceAccount in knext-ci-rbac.yaml. The
# action REFUSES an over-broad credential rather than using it, so a
# cluster-admin kubeconfig will fail with the Role to apply instead.
name: Deploy to Kubernetes (knext)

on:
  push:
    branches: [main]
  workflow_dispatch:

# The workflow itself needs no write scope: the deploy credential is the
# kubeconfig secret, not the GitHub token. \`packages: write\` is here only for
# pushing to GHCR, and can be dropped if you push elsewhere.
permissions:
  contents: read
  packages: write

concurrency:
  # One deploy at a time per branch. Two concurrent applies of the same
  # resource race, and the loser silently wins on the next reconcile.
  group: knext-deploy-\${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: getknext-dev/knext/packages/kn-next-action@v1
        with:
          working-directory: ${appDir}
          kubeconfig: \${{ secrets.KNEXT_KUBECONFIG }}
          namespace: \${{ secrets.KNEXT_NAMESPACE }}
          registry: \${{ secrets.KNEXT_REGISTRY }}
          registry-token: \${{ secrets.KNEXT_REGISTRY_TOKEN || github.token }}
`;
}

export interface InitCiResult {
    written: string[];
    skipped: string[];
}

/**
 * #1535: the ONE actionable sentence for a file `init-ci` skipped because it
 * already exists — names the file, points at the fix (`--force`). Pure and
 * exported so it is testable without capturing pino's log stream, which
 * writes through its own destination rather than `process.stdout.write`.
 */
export function skippedFileMessage(relativePath: string): string {
    return `${relativePath} already exists — left alone (use --force to overwrite)`;
}

/**
 * Write both files under `repoRoot`.
 *
 * Refuses to overwrite by default. A workflow file is something the client will
 * have edited — clobbering it to "help" is how a generator earns a reputation
 * for being unsafe to re-run.
 */
export function initCi(
    repoRoot: string,
    opts: { namespace: string; appDir: string; force?: boolean },
): InitCiResult {
    const root = resolve(repoRoot);
    const files: [string, string][] = [
        [WORKFLOW_PATH, renderWorkflow(opts.appDir)],
        [RBAC_PATH, renderRbacManifest(opts.namespace)],
    ];

    const written: string[] = [];
    const skipped: string[] = [];
    for (const [rel, body] of files) {
        const abs = join(root, rel);
        if (existsSync(abs) && !opts.force) {
            skipped.push(rel);
            continue;
        }
        mkdirSync(dirname(abs), { recursive: true });
        writeFileSync(abs, body);
        written.push(rel);
    }
    return { written, skipped };
}

/** Where the minted kubeconfig lands by default (#1533). */
export const MINTED_KUBECONFIG_PATH = "knext-deployer.kubeconfig";

/**
 * The commands that mint a kubeconfig for the `knext-deployer`
 * ServiceAccount (#1533, ADR-0061): a `kubectl create token` bound to the
 * ServiceAccount `knext-ci-rbac.yaml` creates, plus the four `kubectl
 * config set-*` calls that assemble a standalone kubeconfig file around it.
 *
 * knext MINTS NOTHING ITSELF — these are PRINTED for the user to run in
 * their own shell, against their own kube-context. Every one of them is a
 * read of the local kubeconfig or a `TokenRequest` for a ServiceAccount the
 * user already owns; none of it is a knext-held credential or a knext
 * process holding a cluster session (ADR-0061's "does not own" list:
 * kubeconfig acquisition stays the user's).
 *
 * A bearer token, not an exec plugin — the ONE shape
 * `classifyKubeconfigSafety` (kubeconfig-safety.ts) accepts, on every
 * cloud, because it never shells out to a cloud CLI for cloud-account
 * credentials.
 */
export function mintKubeconfigCommands(namespace: string): string[] {
    const sa = "knext-deployer";
    const out = MINTED_KUBECONFIG_PATH;
    return [
        // Removed first so re-running this WHOLE recipe (the documented
        // renewal path, round 4 of #1557, R3-B1) always starts from a fresh
        // `kubectl config set-*` output rather than patching an already-
        // patched file. Without this, renewal has nothing to reset the
        // `users: null` anchor the patch line below depends on.
        `rm -f -- "${out}"`,
        `SERVER=$(kubectl config view --minify --raw -o jsonpath='{.clusters[0].cluster.server}')`,
        `CA_DATA=$(kubectl config view --minify --raw -o jsonpath='{.clusters[0].cluster.certificate-authority-data}')`,
        // Empty when the source kubeconfig points at a CA FILE or skips TLS
        // verification — the set-cluster line would then embed an empty CA
        // and every CI connection would fail TLS. Say so before writing.
        `[ -n "$CA_DATA" ] || echo "warning: your kubeconfig has no embedded CA (it points at a CA file, or skips TLS verification), so the minted kubeconfig would have an EMPTY certificate authority. Set CA_DATA=\\$(base64 < /path/to/ca.crt | tr -d '\\n') and continue." >&2`,
        // A one-year bound token by default — adjust --duration to your
        // rotation policy; the cluster may cap it lower (server flag
        // --service-account-max-token-expiration).
        `TOKEN=$(kubectl create token ${sa} -n ${namespace} --duration=8760h)`,
        `kubectl config set-cluster ${sa} --server="$SERVER" --certificate-authority=/dev/stdin --embed-certs=true --kubeconfig=${out} <<< "$(echo "$CA_DATA" | base64 -d)"`,
        `kubectl config set-context ${sa} --cluster=${sa} --user=${sa} --namespace=${namespace} --kubeconfig=${out}`,
        `kubectl config use-context ${sa} --kubeconfig=${out}`,
        // The token is written by patching the file, never by a `kubectl
        // ... --token="$TOKEN"` call: `kubectl config set-credentials` has no
        // stdin/file form for --token (verified against its own --help), so
        // that flag would put the bearer token in THIS process's argv,
        // readable via `ps` by any other local user for the life of the
        // (brief) child process — the same class of exposure `--push-secret`
        // avoids for the push step. `$(<file)`, `${VAR/…/…}` and `printf` are
        // bash BUILTINS: none of them fork+exec, so the token never appears
        // in any process's argument list. `users: null` is exactly what the
        // three kubectl calls above leave in a freshly-written kubeconfig
        // (their own marshalling of a nil slice) — patched here to a real
        // entry instead of asking kubectl to write it.
        //
        // Fails CLOSED when that anchor is missing (round 4 of #1557,
        // R3-B1): a file that already has a `users:` entry — which is what
        // running only this line and the TOKEN= line above it, over an
        // EXISTING kubeconfig, produces — matches nothing, so the
        // substitution used to be a silent no-op that left the OLD token in
        // place while exiting 0. Renewal is now "re-run the whole recipe" (it
        // deletes its own output first), and this refuses rather than
        // pretend it rotated anything if that is skipped.
        `KNEXT_KUBECONFIG_TEXT=$(<${out}); case "$KNEXT_KUBECONFIG_TEXT" in *'users: null'*) ;; *) echo "knext: ${out} already has a users: entry, so patching it here would silently keep the OLD token. Delete ${out} and re-run the whole recipe from the top (it re-creates ${out} for you) to mint a fresh one." >&2; exit 1 ;; esac; NEW_USERS=$'users:\\n- name: '"${sa}"$'\\n  user:\\n    token: '"$TOKEN"; printf '%s\\n' "\${KNEXT_KUBECONFIG_TEXT/users: null/$NEW_USERS}" > ${out}`,
    ];
}

/** The post-generation instructions, so the next step is never a guess. */
export function nextSteps(namespace: string): string {
    const mint = mintKubeconfigCommands(namespace)
        .map((c) => `       ${c}`)
        .join("\n");
    return [
        "Next, in this order:",
        "",
        `  1. Read ${RBAC_PATH}, then:  kubectl apply -f ${RBAC_PATH}`,
        "  2. Mint a kubeconfig for the knext-deployer ServiceAccount",
        "     (knext writes nothing to the cluster — you run these):",
        "",
        mint,
        "",
        `  3. Add ${MINTED_KUBECONFIG_PATH}, base64-encoded, as the ` +
            "KNEXT_KUBECONFIG secret — or run:",
        `       kn-next init-ci --namespace ${namespace} --push-secret ` +
            `${MINTED_KUBECONFIG_PATH}`,
        "     which reads that file and pushes it with `gh secret set`" +
            " itself (the token is never printed).",
        "  4. Add the other three secrets listed at the top of",
        `     ${WORKFLOW_PATH}.`,
        "  5. Push. The operator reconciles from the resource CI writes.",
        "",
        `The credential grants ${CI_ROLE_RULES[0].verbs.join("/")} on ` +
            `${CI_ROLE_RULES[0].resources[0]} in ${namespace}, and nothing else.`,
        "The token expires after one year (--duration=8760h) and CI then " +
            "fails to authenticate. Before that, re-run the WHOLE recipe " +
            "above from the top and push the secret again — it deletes its " +
            `own ${MINTED_KUBECONFIG_PATH} first, so the renewed token ` +
            "replaces the old one. Re-running only the last two lines over " +
            "an existing file leaves the old token in place and refuses " +
            "instead of pretending to rotate it. Deleting and recreating " +
            "the knext-deployer ServiceAccount revokes it early.",
    ].join("\n");
}
