/**
 * `knext init-ci --provider gitlab` (#1534) — the GitLab CI/CD counterpart of
 * `renderWorkflow` (init-ci.ts, the GitHub Actions template). Same base as
 * ADR-0049 stage 1: knext hosts nothing, holds no credentials, and the
 * generated pipeline writes ONE kind of object to the cluster via `kn-next
 * deploy` — nothing here re-derives that.
 *
 * ## Same preflight, reused rather than re-derived
 *
 * The two refusals `packages/kn-next-action` runs before any cluster call
 * are exposed as CLI verbs so a non-GitHub pipeline can invoke them without a
 * shell script re-deriving the rules:
 *
 *   1. `knext doctor --ci-kubeconfig <path>` — the ADR-0061 exec/auth-provider
 *      refusal (`kubeconfig-safety.ts`), a LOCAL file read, no cluster call.
 *   2. `knext ci-preflight --namespace <ns>` — the ADR-0049/#1495
 *      rules-review + hazard spot-check (`credential-scope.ts`), the CLI
 *      verb `ci-preflight-cmd.ts` exposes so this template (and any future
 *      non-GitHub provider) can run the SAME check `kn-next-action`'s
 *      `preflight.mjs` runs, through the published CLI instead of a copy.
 *
 * Both run in their own `preflight` stage, `credential-preflight` declared
 * `needs: [kubeconfig-check]` so the exec-plugin refusal always completes
 * BEFORE `ci-preflight` ever shells out to kubectl — mirroring
 * `kn-next-action/action.yml`'s step order. `deploy` needs both. Neither
 * preflight job sets `allow_failure` — GitLab's default (a job failure fails
 * the pipeline) is exactly "not skippable", so nothing here may set it `true`.
 */
import { cliVersion } from "../create";
import { REQUIRED_SECRETS } from "./ci-secrets";

/** Where the generated pipeline lands, relative to the repo root. */
export const GITLAB_CI_PATH = ".gitlab-ci.yml";

/**
 * The pipeline. `appDir` is baked in at generation time (like `renderWorkflow`'s
 * `working-directory`); the CLI invocation itself is a CI/CD variable
 * (`KNEXT_CLI`) so it can be overridden — e.g. by this repo's own dogfooding
 * pipeline, or by a hermetic test — the same seam `kn-next-action`'s `cli`
 * input gives the GitHub template.
 */
export function renderGitlabPipeline(appDir: string): string {
    const varDocs = REQUIRED_SECRETS.map(
        (s) =>
            `#   ${s.name.padEnd(21)} ${s.what}\n#   ${" ".repeat(21)} ${s.why}`,
    ).join("\n");
    const pinnedCli = `npx --yes @getknext/core@${cliVersion()}`;

    return `# Generated by \`knext init-ci --provider gitlab\`.
#
# Deploys this repository to YOUR cluster on YOUR cloud. knext hosts nothing
# and holds no credentials — every job below runs on your own GitLab Runner,
# against a cluster you control.
#
# CI/CD variables this needs (Settings -> CI/CD -> Variables). Mark EVERY one
# BOTH Masked (never shown in a job log) AND Protected (only available to
# jobs running on protected branches/tags — this pipeline only runs on
# \`main\`, which you should protect):
${varDocs}
#
# KNEXT_KUBECONFIG is a base64-encoded TEXT variable (type "Variable", not
# "File") — the exact same value \`kn-next init-ci --push-secret\` and the
# mint recipe below produce for the GitHub template, decoded the same way.
# The kubeconfig must belong to the ServiceAccount in knext-ci-rbac.yaml. The
# preflight jobs below REFUSE an over-broad credential rather than using it,
# so a cluster-admin kubeconfig fails on the Role to apply instead — same
# refusal, same message, as the GitHub Action.

stages:
  - preflight
  - deploy

variables:
  # Override to point at a different CLI invocation (a local checkout's
  # built dist, a pinned alternate version, …) without editing every job.
  KNEXT_CLI: "${pinnedCli}"

.knext_kubeconfig: &knext_kubeconfig
  - mkdir -p "$CI_PROJECT_DIR/.knext"
  - printf '%s' "$KNEXT_KUBECONFIG" | base64 -d > "$CI_PROJECT_DIR/.knext/kubeconfig"
  - export KUBECONFIG="$CI_PROJECT_DIR/.knext/kubeconfig"
  - chmod 600 "$KUBECONFIG"

.knext_kubectl_install: &knext_kubectl_install
  - |
    if ! command -v kubectl >/dev/null 2>&1; then
      curl -fsSLO "https://dl.k8s.io/release/$(curl -fsSL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x kubectl
      mv kubectl /usr/local/bin/kubectl
    fi

# ── Kubeconfig check — ALWAYS runs, never conditional on the hazard check ──
# ADR-0061: an exec/auth-provider kubeconfig runs a cloud CLI on this runner
# with a cloud account's credentials in scope. Its own job — not a step inside
# credential-preflight — so nothing can special-case it away the way an
# \`allow_failure\`/\`when: manual\` on a shared job could.
kubeconfig-check:
  stage: preflight
  image: node:22
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - *knext_kubeconfig
    - $KNEXT_CLI doctor --ci-kubeconfig "$KUBECONFIG"

# ── Credential preflight — refuse more than we asked for ────────────────────
# ADR-0049/#1495: a cluster-admin kubeconfig, or one with any grant outside
# the published Role, must be refused, not merely discouraged. Depends on
# kubeconfig-check so the exec-plugin refusal always runs BEFORE this job's
# first kubectl call.
credential-preflight:
  stage: preflight
  image: node:22
  needs:
    - kubeconfig-check
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - *knext_kubeconfig
    - *knext_kubectl_install
    - $KNEXT_CLI ci-preflight --namespace "$KNEXT_NAMESPACE" --kubeconfig "$KUBECONFIG"

deploy:
  stage: deploy
  image: node:22
  needs:
    - kubeconfig-check
    - credential-preflight
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - *knext_kubeconfig
    - *knext_kubectl_install
    - cd ${appDir}
    - npm ci
    - $KNEXT_CLI deploy --namespace "$KNEXT_NAMESPACE" --registry "$KNEXT_REGISTRY"
`;
}
