/**
 * `kn-next init-ci` — ADR-0049 stage 1, the client-side setup (#874).
 *
 * Generates the two files a client needs to deploy from their own repository to
 * their own cluster: the workflow, and the RBAC manifest that creates the
 * scoped credential the workflow uses.
 *
 * ## Why generate the RBAC rather than document it
 *
 * The alternative is a docs page saying "create a ServiceAccount and bind this
 * Role". People paste from docs pages, and what they paste when the scoped path
 * is fiddly is `cluster-admin` — which is exactly the credential ADR-0049
 * requires the Action to refuse. Generating a manifest they can read, diff and
 * `kubectl apply` makes the narrow path the easy one, which is the only version
 * of a security control that survives contact with a hurry.
 *
 * It writes files and touches no cluster, like `create` and unlike `deploy`.
 * The client applies the manifest themselves — knext never holds their
 * credentials, which is the whole point of stage 1.
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { CI_ROLE_RULES, renderRoleYaml } from "./credential-scope";

/** Where each generated file lands, relative to the repo root. */
export const WORKFLOW_PATH = ".github/workflows/knext-deploy.yml";
export const RBAC_PATH = "knext-ci-rbac.yaml";

/**
 * The four repository secrets ADR-0049 asks the client for, with the reason
 * each is needed. A user who cannot see why a permission is wanted cannot
 * consent to it, so the reasons ship in the generated file rather than only in
 * a docs page.
 */
export const REQUIRED_SECRETS = [
    {
        name: "KNEXT_KUBECONFIG",
        what: "base64 kubeconfig for the ServiceAccount created by knext-ci-rbac.yaml",
        why: "so the workflow can write the NextApp resource — nothing else",
    },
    {
        name: "KNEXT_NAMESPACE",
        what: "the namespace to deploy into",
        why: "keeps the credential's blast radius to one namespace",
    },
    {
        name: "KNEXT_REGISTRY",
        what: "registry host + repository, e.g. ghcr.io/acme/app",
        why: "where the built image is pushed; you own it, knext never sees it",
    },
    {
        name: "KNEXT_REGISTRY_TOKEN",
        what: "a push token for that registry",
        why: "as above — omit on GHCR, where the built-in GITHUB_TOKEN suffices",
    },
] as const;

/**
 * The RBAC manifest: ServiceAccount, Role, RoleBinding.
 *
 * The Role body comes from `renderRoleYaml`, which reads `CI_ROLE_RULES` —
 * the same constant the preflight classifier checks against. That is not
 * tidiness: if the generator and the check drifted, every client would hit a
 * refusal on the credential knext itself told them to create.
 */
export function renderRbacManifest(namespace: string): string {
    return [
        "# Generated by `kn-next init-ci`. Read it before applying it.",
        "#",
        "# This grants CI permission to write ONE kind of object in ONE",
        "# namespace. It cannot delete your app, cannot read your Secrets, and",
        "# cannot create Deployments or Services — the knext operator does all",
        "# of that, from the resource this credential writes.",
        "#",
        "#   kubectl apply -f knext-ci-rbac.yaml",
        "",
        "apiVersion: v1",
        "kind: ServiceAccount",
        "metadata:",
        "  name: knext-deployer",
        `  namespace: ${namespace}`,
        "---",
        renderRoleYaml(namespace).trimEnd(),
        "---",
        "apiVersion: rbac.authorization.k8s.io/v1",
        "kind: RoleBinding",
        "metadata:",
        "  name: knext-deployer",
        `  namespace: ${namespace}`,
        "roleRef:",
        "  apiGroup: rbac.authorization.k8s.io",
        "  kind: Role",
        "  name: knext-deployer",
        "subjects:",
        "  - kind: ServiceAccount",
        "    name: knext-deployer",
        `    namespace: ${namespace}`,
        "",
    ].join("\n");
}

/**
 * The workflow. Thin by construction — it hands off to the composite action,
 * which hands off to the CLI, which emits a CR and stops.
 */
export function renderWorkflow(appDir: string): string {
    const secretDocs = REQUIRED_SECRETS.map(
        (s) =>
            `#   ${s.name.padEnd(21)} ${s.what}\n#   ${" ".repeat(21)} ${s.why}`,
    ).join("\n");

    return `# Generated by \`kn-next init-ci\`.
#
# Deploys this repository to YOUR cluster on YOUR cloud. knext hosts nothing
# and holds no credentials — everything below runs in your CI, against a
# cluster you control.
#
# Repository secrets this needs (Settings -> Secrets and variables -> Actions):
${secretDocs}
#
# The kubeconfig must belong to the ServiceAccount in knext-ci-rbac.yaml. The
# action REFUSES an over-broad credential rather than using it, so a
# cluster-admin kubeconfig will fail with the Role to apply instead.
name: Deploy to Kubernetes (knext)

on:
  push:
    branches: [main]
  workflow_dispatch:

# The workflow itself needs no write scope: the deploy credential is the
# kubeconfig secret, not the GitHub token. \`packages: write\` is here only for
# pushing to GHCR, and can be dropped if you push elsewhere.
permissions:
  contents: read
  packages: write

concurrency:
  # One deploy at a time per branch. Two concurrent applies of the same
  # resource race, and the loser silently wins on the next reconcile.
  group: knext-deploy-\${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: getknext-dev/knext/packages/kn-next-action@v1
        with:
          working-directory: ${appDir}
          kubeconfig: \${{ secrets.KNEXT_KUBECONFIG }}
          namespace: \${{ secrets.KNEXT_NAMESPACE }}
          registry: \${{ secrets.KNEXT_REGISTRY }}
          registry-token: \${{ secrets.KNEXT_REGISTRY_TOKEN || github.token }}
`;
}

export interface InitCiResult {
    written: string[];
    skipped: string[];
}

/**
 * Write both files under `repoRoot`.
 *
 * Refuses to overwrite by default. A workflow file is something the client will
 * have edited — clobbering it to "help" is how a generator earns a reputation
 * for being unsafe to re-run.
 */
export function initCi(
    repoRoot: string,
    opts: { namespace: string; appDir: string; force?: boolean },
): InitCiResult {
    const root = resolve(repoRoot);
    const files: [string, string][] = [
        [WORKFLOW_PATH, renderWorkflow(opts.appDir)],
        [RBAC_PATH, renderRbacManifest(opts.namespace)],
    ];

    const written: string[] = [];
    const skipped: string[] = [];
    for (const [rel, body] of files) {
        const abs = join(root, rel);
        if (existsSync(abs) && !opts.force) {
            skipped.push(rel);
            continue;
        }
        mkdirSync(dirname(abs), { recursive: true });
        writeFileSync(abs, body);
        written.push(rel);
    }
    return { written, skipped };
}

/** The post-generation instructions, so the next step is never a guess. */
export function nextSteps(namespace: string): string {
    return [
        "Next, in this order:",
        "",
        `  1. Read ${RBAC_PATH}, then:  kubectl apply -f ${RBAC_PATH}`,
        "  2. Create a kubeconfig for the knext-deployer ServiceAccount and",
        `     add it, base64-encoded, as the KNEXT_KUBECONFIG secret.`,
        "  3. Add the other three secrets listed at the top of",
        `     ${WORKFLOW_PATH}.`,
        "  4. Push. The operator reconciles from the resource CI writes.",
        "",
        `The credential grants ${CI_ROLE_RULES[0].verbs.join("/")} on ` +
            `${CI_ROLE_RULES[0].resources[0]} in ${namespace}, and nothing else.`,
    ].join("\n");
}
