// Runtime Entry - Option 3
// Launches the Next.js Standalone Server

export async function start() {
  console.info('[Runtime] Starting Next.js Standalone Server...');

  // Set environment defaults for Knative
  process.env.PORT = process.env.PORT || '8080';
  process.env.HOSTNAME = '0.0.0.0';

  // Path to the server.js generated by output: 'standalone'
  // It should be extracted to /app/apps/file-manager/server.js
  // We search for it just in case structure varies? No, stick to known structure.

  // Note: We use process.cwd() which is /app
  const serverJsPath = `${process.cwd()}/apps/file-manager/server.js`;

  console.info(`[Runtime] Importing ${serverJsPath}...`);

  try {
    // Dynamic import executes the server script
    await import(serverJsPath);
    console.info('[Runtime] Server script executed.');
  } catch (error) {
    console.error('[Runtime] ❌ Failed to start server.js:', error);
    console.error('Verify that the standalone bundle was extracted correctly.');
    // List files for debugging
    const fs = await import('node:fs');
    if (fs.existsSync(`${process.cwd()}/apps`)) {
      console.info('Contents of apps:', fs.readdirSync(`${process.cwd()}/apps/file-manager`));
    } else {
      console.info('/app/apps does not exist!');
    }
  }
}
