//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnextPlatform) DeepCopyInto(out *KnextPlatform) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnextPlatform.
func (in *KnextPlatform) DeepCopy() *KnextPlatform {
	if in == nil {
		return nil
	}
	out := new(KnextPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnextPlatform) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnextPlatformList) DeepCopyInto(out *KnextPlatformList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KnextPlatform, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnextPlatformList.
func (in *KnextPlatformList) DeepCopy() *KnextPlatformList {
	if in == nil {
		return nil
	}
	out := new(KnextPlatformList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnextPlatformList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnextPlatformSpec) DeepCopyInto(out *KnextPlatformSpec) {
	*out = *in
	if in.Scaling != nil {
		in, out := &in.Scaling, &out.Scaling
		*out = new(PlatformScaling)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(PlatformResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(PlatformLimits)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(PlatformDatabase)
		**out = **in
	}
	if in.Rollout != nil {
		in, out := &in.Rollout, &out.Rollout
		*out = new(PlatformRollout)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnextPlatformSpec.
func (in *KnextPlatformSpec) DeepCopy() *KnextPlatformSpec {
	if in == nil {
		return nil
	}
	out := new(KnextPlatformSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnextPlatformStatus) DeepCopyInto(out *KnextPlatformStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rollout != nil {
		in, out := &in.Rollout, &out.Rollout
		*out = new(PlatformRolloutStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnextPlatformStatus.
func (in *KnextPlatformStatus) DeepCopy() *KnextPlatformStatus {
	if in == nil {
		return nil
	}
	out := new(KnextPlatformStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformDatabase) DeepCopyInto(out *PlatformDatabase) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformDatabase.
func (in *PlatformDatabase) DeepCopy() *PlatformDatabase {
	if in == nil {
		return nil
	}
	out := new(PlatformDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformLimits) DeepCopyInto(out *PlatformLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformLimits.
func (in *PlatformLimits) DeepCopy() *PlatformLimits {
	if in == nil {
		return nil
	}
	out := new(PlatformLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformResourceDefaults) DeepCopyInto(out *PlatformResourceDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformResourceDefaults.
func (in *PlatformResourceDefaults) DeepCopy() *PlatformResourceDefaults {
	if in == nil {
		return nil
	}
	out := new(PlatformResourceDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformResources) DeepCopyInto(out *PlatformResources) {
	*out = *in
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(PlatformResourceDefaults)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformResources.
func (in *PlatformResources) DeepCopy() *PlatformResources {
	if in == nil {
		return nil
	}
	out := new(PlatformResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformRollout) DeepCopyInto(out *PlatformRollout) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformRollout.
func (in *PlatformRollout) DeepCopy() *PlatformRollout {
	if in == nil {
		return nil
	}
	out := new(PlatformRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformRolloutStatus) DeepCopyInto(out *PlatformRolloutStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformRolloutStatus.
func (in *PlatformRolloutStatus) DeepCopy() *PlatformRolloutStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformRolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformScaling) DeepCopyInto(out *PlatformScaling) {
	*out = *in
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(PlatformScalingDefaults)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformScaling.
func (in *PlatformScaling) DeepCopy() *PlatformScaling {
	if in == nil {
		return nil
	}
	out := new(PlatformScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformScalingDefaults) DeepCopyInto(out *PlatformScalingDefaults) {
	*out = *in
	if in.TargetBurstCapacity != nil {
		in, out := &in.TargetBurstCapacity, &out.TargetBurstCapacity
		*out = new(int32)
		**out = **in
	}
	if in.PanicWindowPercentage != nil {
		in, out := &in.PanicWindowPercentage, &out.PanicWindowPercentage
		*out = new(int32)
		**out = **in
	}
	if in.PanicThresholdPercentage != nil {
		in, out := &in.PanicThresholdPercentage, &out.PanicThresholdPercentage
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformScalingDefaults.
func (in *PlatformScalingDefaults) DeepCopy() *PlatformScalingDefaults {
	if in == nil {
		return nil
	}
	out := new(PlatformScalingDefaults)
	in.DeepCopyInto(out)
	return out
}
